# Generated by Django 5.1.3 on 2024-11-05 08:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(default='default@example.com', max_length=254)),
                ('direccion', models.CharField(default='sin_direccion', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Copa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('banco', models.CharField(choices=[('Caixa', 'Caixa'), ('BBVA', 'BBVA'), ('UNICAJA', 'UNICAJA'), ('ING', 'ING')], max_length=20)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='examenApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
                ('prioridad', models.IntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenApp.cliente')),
                ('copa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenApp.copa')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='copas_favoritas',
            field=models.ManyToManyField(related_name='clientes_favoritos', through='examenApp.Favoritas', to='examenApp.copa'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenApp.cliente')),
                ('copa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='examenApp.copa')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
